//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.Artists = new HashSet<Artist>();
            this.Bands = new HashSet<Band>();
            this.AgentComments = new HashSet<AgentComment>();
        }
    
        public int Agent_Id { get; set; }
        public string Agent_Name { get; set; }
        public string Agent_Description { get; set; }
        public string Agent_Url { get; set; }
        public byte[] Agent_Photo { get; set; }
        public string Agent_PhotoFileName { get; set; }
        public string Agent_PhotoMimeType { get; set; }
        public Nullable<int> Agent_CreatedBy { get; set; }
        public Nullable<System.DateTime> Agent_CreatedDate { get; set; }
    
        public virtual ICollection<Artist> Artists { get; set; }
        public virtual ICollection<Band> Bands { get; set; }
        public virtual ICollection<AgentComment> AgentComments { get; set; }
    }
}
