//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentComment
    {
        public long AgentComment_Id { get; set; }
        public long AgentComment_CommentId { get; set; }
        public int AgentComment_AgentId { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Comment Comment { get; set; }
    }
}
