//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistBand
    {
        public int ArtistBand_ArtistId { get; set; }
        public int ArtistBand_BandId { get; set; }
        public Nullable<System.DateTime> ArtistBand_StartDate { get; set; }
        public Nullable<System.DateTime> ArtistBand_EndDate { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Band Band { get; set; }
    }
}
