//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistMediaType
    {
        public ArtistMediaType()
        {
            this.ArtistMedias = new HashSet<ArtistMedia>();
        }
    
        public int ArtistMediaType_Id { get; set; }
        public string ArtistMediaType_Name { get; set; }
    
        public virtual ICollection<ArtistMedia> ArtistMedias { get; set; }
    }
}
