//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistComment
    {
        public int ArtistComment_Id { get; set; }
        public int ArtistComment_ArtistId { get; set; }
        public int ArtistComment_UserId { get; set; }
        public string ArtistComment_Comment { get; set; }
        public Nullable<System.DateTime> ArtistComment_DateTime { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual User User { get; set; }
    }
}
