//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistType
    {
        public int ArtistType_ArtistId { get; set; }
        public int ArtistType_TypeId { get; set; }
        public string ArtistType_Notes { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Type Type { get; set; }
    }
}
