//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistMedia
    {
        public int ArtistMedia_Id { get; set; }
        public int ArtistMedia_ArtistId { get; set; }
        public string ArtistMedia_Name { get; set; }
        public int ArtistMedia_TypeId { get; set; }
        public string ArtistMedia_Link { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual ArtistMediaType ArtistMediaType { get; set; }
    }
}
