//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistUser
    {
        public int ArtistUser_Id { get; set; }
        public int ArtistUser_ArtistId { get; set; }
        public int ArtistUser_UserId { get; set; }
        public string ArtistUser_Note { get; set; }
        public Nullable<System.DateTime> ArtistUser_DateTime { get; set; }
        public Nullable<decimal> ArtistUser_UserRating { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual User User { get; set; }
    }
}
