//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Band
    {
        public Band()
        {
            this.ArtistBands = new HashSet<ArtistBand>();
            this.BandUsers = new HashSet<BandUser>();
            this.Events = new HashSet<Event>();
            this.BandComments = new HashSet<BandComment>();
        }
    
        public int Band_Id { get; set; }
        public string Band_Name { get; set; }
        public string Band_Description { get; set; }
        public Nullable<System.DateTime> Band_StartDate { get; set; }
        public Nullable<System.DateTime> Band_EndDate { get; set; }
        public Nullable<int> Band_BandTypeId { get; set; }
        public Nullable<int> Band_AgentId { get; set; }
        public Nullable<int> Band_VenueId { get; set; }
        public byte[] Band_Photo { get; set; }
        public string Band_PhotoFileName { get; set; }
        public string Band_PhotoMimeType { get; set; }
        public Nullable<int> Band_CountryId { get; set; }
        public Nullable<int> Band_StateProvinceId { get; set; }
        public string Band_City { get; set; }
        public Nullable<int> Band_CreatedBy { get; set; }
        public Nullable<System.DateTime> Band_CreatedDate { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual ICollection<ArtistBand> ArtistBands { get; set; }
        public virtual BandType BandType { get; set; }
        public virtual CountryRegion CountryRegion { get; set; }
        public virtual StateProvince StateProvince { get; set; }
        public virtual Venue Venue { get; set; }
        public virtual ICollection<BandUser> BandUsers { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<BandComment> BandComments { get; set; }
    }
}
