//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BandUser
    {
        public int BandUser_Id { get; set; }
        public int BandUser_BandId { get; set; }
        public int BandUser_UserId { get; set; }
        public string BandUser_Note { get; set; }
        public Nullable<System.DateTime> BandUser_DateTime { get; set; }
        public Nullable<decimal> BandUser_UserRating { get; set; }
    
        public virtual Band Band { get; set; }
    }
}
