//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BandComment
    {
        public long BandComment_Id { get; set; }
        public long BandComment_CommentId { get; set; }
        public int BandComment_BandId { get; set; }
    
        public virtual Band Band { get; set; }
        public virtual Comment Comment { get; set; }
    }
}
