//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.AgentComments = new HashSet<AgentComment>();
            this.ArtistComments = new HashSet<ArtistComment>();
            this.BandComments = new HashSet<BandComment>();
            this.EventComments = new HashSet<EventComment>();
            this.PerformanceComments = new HashSet<PerformanceComment>();
            this.PieceComments = new HashSet<PieceComment>();
            this.ReviewComments = new HashSet<ReviewComment>();
            this.RoleComments = new HashSet<RoleComment>();
            this.VenueComments = new HashSet<VenueComment>();
            this.PhotoComments = new HashSet<PhotoComment>();
            this.ProductionComments = new HashSet<ProductionComment>();
        }
    
        public long Comment_Id { get; set; }
        public string Comment_Text { get; set; }
        public int Comment_UserId { get; set; }
        public Nullable<System.DateTime> Comment_DateTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<AgentComment> AgentComments { get; set; }
        public virtual ICollection<ArtistComment> ArtistComments { get; set; }
        public virtual ICollection<BandComment> BandComments { get; set; }
        public virtual ICollection<EventComment> EventComments { get; set; }
        public virtual ICollection<PerformanceComment> PerformanceComments { get; set; }
        public virtual ICollection<PieceComment> PieceComments { get; set; }
        public virtual ICollection<ReviewComment> ReviewComments { get; set; }
        public virtual ICollection<RoleComment> RoleComments { get; set; }
        public virtual ICollection<VenueComment> VenueComments { get; set; }
        public virtual ICollection<PhotoComment> PhotoComments { get; set; }
        public virtual ICollection<ProductionComment> ProductionComments { get; set; }
    }
}
