//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;

    public partial class CountryRegion
    {
        public CountryRegion()
        {
            this.Artists = new HashSet<Artist>();
            this.Bands = new HashSet<Band>();
            this.StateProvinces = new HashSet<StateProvince>();
            this.Users = new HashSet<User>();
            this.Venues = new HashSet<Venue>();
        }

        public int CountryRegion_Id { get; set; }
        public string CountryRegion_Code { get; set; }

        [Required]
        [Display(Name = "Country")]
        public string CountryRegion_Name { get; set; }

        public virtual ICollection<Artist> Artists { get; set; }
        public virtual ICollection<Band> Bands { get; set; }
        public virtual ICollection<StateProvince> StateProvinces { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Venue> Venues { get; set; }
    }
}
