//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventUserStatus
    {
        public EventUserStatus()
        {
            this.EventUsers = new HashSet<EventUser>();
        }
    
        public int EventUserStatus_Id { get; set; }
        public string EventUserStatus_Name { get; set; }
        public string EventUserStatus_Future { get; set; }
        public string EventUserStatus_Past { get; set; }
    
        public virtual ICollection<EventUser> EventUsers { get; set; }
    }
}
