//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventComment
    {
        public int EventComment_Id { get; set; }
        public int EventComment_EventId { get; set; }
        public int EventComment_UserId { get; set; }
        public string EventComment_Comment { get; set; }
        public Nullable<System.DateTime> EventComment_DateTime { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
