//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public Genre()
        {
            this.Events = new HashSet<Event>();
            this.Genre1 = new HashSet<Genre>();
            this.Pieces = new HashSet<Piece>();
            this.Roles = new HashSet<Role>();
        }
    
        public int Genre_Id { get; set; }
        public string Genre_Name { get; set; }
        public Nullable<int> Genre_ParentId { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Genre> Genre1 { get; set; }
        public virtual Genre Genre2 { get; set; }
        public virtual ICollection<Piece> Pieces { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
