//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceComment
    {
        public long PerformanceComment_Id { get; set; }
        public long PerformanceComment_CommentId { get; set; }
        public int PerformanceComment_PerformanceId { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Performance Performance { get; set; }
    }
}
