//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;

    public partial class Performance
    {
        public Performance()
        {
            this.PerformanceArtists = new HashSet<PerformanceArtist>();
            this.ReviewPerformances = new HashSet<ReviewPerformance>();
            this.PerformanceComments = new HashSet<PerformanceComment>();
        }

        public int Performance_Id { get; set; }
        public Nullable<int> Performance_EventId { get; set; }

        [Display(Name = "Piece")]
        public int Performance_PieceId { get; set; }

        [Display(Name = "Production")]
        public Nullable<int> Performance_ProductionId { get; set; }

        [Display(Name = "Order")]
        public Nullable<int> Performance_Order { get; set; }

        public byte[] Performance_Photo { get; set; }
        public string Performance_PhotoFileName { get; set; }
        public string Performance_PhotoMimeType { get; set; }

        public int Performance_CreatedBy { get; set; }
        public Nullable<System.DateTime> Performance_CreatedDate { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Piece Piece { get; set; }
        public virtual Production Production { get; set; }
        public virtual ICollection<PerformanceArtist> PerformanceArtists { get; set; }
        public virtual ICollection<ReviewPerformance> ReviewPerformances { get; set; }
        public virtual ICollection<PerformanceComment> PerformanceComments { get; set; }
    }
}
