//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceArtistUser
    {
        public int PerformanceArtistUser_Id { get; set; }
        public int PerformanceArtistUser_PerformanceArtistId { get; set; }
        public int PerformanceArtistUser_UserId { get; set; }
        public string PerformanceArtistUser_Note { get; set; }
        public Nullable<System.DateTime> PerformanceArtistUser_DateTime { get; set; }
        public Nullable<int> PerformanceArtistUser_Rating { get; set; }
    
        public virtual PerformanceArtist PerformanceArtist { get; set; }
    }
}
