//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public Photo()
        {
            this.PhotoAgents = new HashSet<PhotoAgent>();
            this.PhotoArtists = new HashSet<PhotoArtist>();
            this.PhotoBands = new HashSet<PhotoBand>();
            this.PhotoEvents = new HashSet<PhotoEvent>();
            this.PhotoPerformances = new HashSet<PhotoPerformance>();
            this.PhotoProductions = new HashSet<PhotoProduction>();
            this.PhotoReviews = new HashSet<PhotoReview>();
            this.PhotoVenues = new HashSet<PhotoVenue>();
        }
    
        public int Photo_Id { get; set; }
        public byte[] Photo_Photo { get; set; }
        public string Photo_PhotoFileName { get; set; }
        public string Photo_PhotoMimeType { get; set; }
        public string Photo_Caption { get; set; }
        public Nullable<int> Photo_CreatedBy { get; set; }
        public Nullable<System.DateTime> Photo_CreatedDate { get; set; }
    
        public virtual ICollection<PhotoAgent> PhotoAgents { get; set; }
        public virtual ICollection<PhotoArtist> PhotoArtists { get; set; }
        public virtual ICollection<PhotoBand> PhotoBands { get; set; }
        public virtual ICollection<PhotoEvent> PhotoEvents { get; set; }
        public virtual ICollection<PhotoPerformance> PhotoPerformances { get; set; }
        public virtual ICollection<PhotoProduction> PhotoProductions { get; set; }
        public virtual ICollection<PhotoReview> PhotoReviews { get; set; }
        public virtual ICollection<PhotoVenue> PhotoVenues { get; set; }
    }
}
