//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public Photo()
        {
            this.PhotoComments = new HashSet<PhotoComment>();
        }
    
        public int Photo_Id { get; set; }
        public byte[] Photo_Photo { get; set; }
        public string Photo_PhotoFileName { get; set; }
        public string Photo_PhotoMimeType { get; set; }
        public string Photo_Caption { get; set; }
        public Nullable<int> Photo_CreatedBy { get; set; }
        public Nullable<System.DateTime> Photo_CreatedDate { get; set; }
    
        public virtual ICollection<PhotoComment> PhotoComments { get; set; }
    }
}
