//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoVenue
    {
        public int PhotoVenue_Id { get; set; }
        public int PhotoVenue_PhotoId { get; set; }
        public int PhotoVenue_VenueId { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual Venue Venue { get; set; }
    }
}
