//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoComment
    {
        public long PhotoComment_Id { get; set; }
        public long PhotoComment_CommentId { get; set; }
        public int PhotoComment_PhotoId { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Photo Photo { get; set; }
    }
}
