//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoReview
    {
        public int PhotoReview_Id { get; set; }
        public int PhotoReview_PhotoId { get; set; }
        public int PhotoReview_ReviewId { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual Review Review { get; set; }
    }
}
