//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoPerformance
    {
        public int PhotoPerformance_Id { get; set; }
        public int PhotoPerformance_PhotoId { get; set; }
        public int PhotoPerformance_PerformanceId { get; set; }
    
        public virtual Performance Performance { get; set; }
        public virtual Photo Photo { get; set; }
    }
}
