//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;
    
    public partial class PieceArtist
    {
        public int PieceArtist_Id { get; set; }

        [Display(Name = "Piece")]
        public int PieceArtist_PieceId { get; set; }

        [Display(Name = "Artist")]
        public int PieceArtist_ArtistId { get; set; }

        [Display(Name = "Type")]
        public Nullable<int> PieceArtist_PieceArtistTypeId { get; set; }

        [Display(Name = "Comments")]
        public string PieceArtist_Comments { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Piece Piece { get; set; }
        public virtual PieceArtistType PieceArtistType { get; set; }
    }
}
