//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PieceArtistType
    {
        public PieceArtistType()
        {
            this.PieceArtists = new HashSet<PieceArtist>();
        }
    
        public int PieceArtistType_Id { get; set; }
        public string PieceArtistType_Name { get; set; }
    
        public virtual ICollection<PieceArtist> PieceArtists { get; set; }
    }
}
