//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PieceComment
    {
        public int PieceComment_Id { get; set; }
        public int PieceComment_PieceId { get; set; }
        public int PieceComment_UserId { get; set; }
        public string PieceComment_Comment { get; set; }
        public Nullable<System.DateTime> PieceComment_DateTime { get; set; }
    
        public virtual Piece Piece { get; set; }
    }
}
