//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PiecePhoto
    {
        public long PiecePhoto_Id { get; set; }
        public long PiecePhoto_PhotoId { get; set; }
        public long PiecePhoto_PieceId { get; set; }
    }
}
