//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;

    public partial class Piece
    {
        public Piece()
        {
            this.Performances = new HashSet<Performance>();
            this.PieceArtists = new HashSet<PieceArtist>();
            this.PieceComments = new HashSet<PieceComment>();
            this.Productions = new HashSet<Production>();
            this.Roles = new HashSet<Role>();
        }

        public int Piece_Id { get; set; }

        [Required]
        [Display(Name = "Piece")]
        public string Piece_Name { get; set; }

        [Display(Name = "Year")]
        public Nullable<int> Piece_Year { get; set; }

        [Display(Name = "Description")]
        public string Piece_Description { get; set; }

        public byte[] Piece_Photo { get; set; }
        public string Piece_PhotoFileName { get; set; }
        public string Piece_PhotoMimeType { get; set; }

        [Display(Name = "Genre")]
        public Nullable<int> Piece_GenreId { get; set; }

        public Nullable<int> Piece_CreatedBy { get; set; }
        public Nullable<System.DateTime> Piece_CreatedDate { get; set; }

        [Display(Name = "Wiki")]
        public string Piece_Wiki { get; set; }

        public virtual Genre Genre { get; set; }
        public virtual ICollection<Performance> Performances { get; set; }
        public virtual ICollection<PieceArtist> PieceArtists { get; set; }
        public virtual ICollection<PieceComment> PieceComments { get; set; }
        public virtual ICollection<Production> Productions { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
