//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionArtist
    {
        public int ProductionArtist_Id { get; set; }
        public int ProductionArtist_ProductionId { get; set; }
        public int ProductionArtist_ArtistId { get; set; }
        public string ProductionArtist_Comments { get; set; }
        public byte[] ProductionArtist_Photo { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Production Production { get; set; }
    }
}
