//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionComment
    {
        public long ProductionComment_Id { get; set; }
        public long ProductionComment_CommentId { get; set; }
        public int ProductionComment_ProductionId { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Production Production { get; set; }
    }
}
