//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewVenue
    {
        public int ReviewVenue_Id { get; set; }
        public int ReviewVenue_ReviewId { get; set; }
        public int ReviewVenue_VenueId { get; set; }
        public string ReviewVenue_Comment { get; set; }
        public decimal ReviewVenue_Rating { get; set; }
    
        public virtual Review Review { get; set; }
        public virtual Venue Venue { get; set; }
    }
}
