//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewProduction
    {
        public int ReviewProduction_Id { get; set; }
        public int ReviewProduction_ReviewId { get; set; }
        public int ReviewProduction_ProductionId { get; set; }
        public string ReviewProduction_Comment { get; set; }
        public decimal ReviewProduction_Rating { get; set; }
    
        public virtual Production Production { get; set; }
        public virtual Review Review { get; set; }
    }
}
