//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewPerformance
    {
        public int ReviewPerformance_Id { get; set; }
        public int ReviewPerformance_ReviewId { get; set; }
        public int ReviewPerformance_PerformanceId { get; set; }
        public string ReviewPerformance_Comment { get; set; }
        public decimal ReviewPerformance_Rating { get; set; }
    
        public virtual Performance Performance { get; set; }
        public virtual Review Review { get; set; }
    }
}
