//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public Review()
        {
            this.PhotoReviews = new HashSet<PhotoReview>();
            this.ReviewPerformanceArtists = new HashSet<ReviewPerformanceArtist>();
            this.ReviewProductions = new HashSet<ReviewProduction>();
            this.ReviewVenues = new HashSet<ReviewVenue>();
        }
    
        public int Review_Id { get; set; }
        public int Review_EventId { get; set; }
        public string Review_Title { get; set; }
        public string Review_Comment { get; set; }
        public Nullable<decimal> Review_Rating { get; set; }
        public Nullable<int> Review_UserId { get; set; }
        public Nullable<System.DateTime> Review_Date { get; set; }
        public string Review_Source { get; set; }
        public string Review_URL { get; set; }
        public Nullable<int> Review_CreatedBy { get; set; }
        public Nullable<System.DateTime> Review_CreatedDate { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ICollection<PhotoReview> PhotoReviews { get; set; }
        public virtual ReviewPerformance ReviewPerformance { get; set; }
        public virtual ICollection<ReviewPerformanceArtist> ReviewPerformanceArtists { get; set; }
        public virtual ICollection<ReviewProduction> ReviewProductions { get; set; }
        public virtual ICollection<ReviewVenue> ReviewVenues { get; set; }
    }
}
