//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePhoto
    {
        public long RolePhoto_Id { get; set; }
        public long RolePhoto_PhotoId { get; set; }
        public long RolePhoto_RoleId { get; set; }
    }
}
