//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFriend
    {
        public long UserFriend_Id { get; set; }
        public long UserFriend_UserFacebookId { get; set; }
        public long UserFriend_FriendFacebookId { get; set; }
        public string UserFriend_Name { get; set; }
    }
}
