//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenueComment
    {
        public int VenueComment_Id { get; set; }
        public int VenueComment_VenueId { get; set; }
        public int VenueComment_UserId { get; set; }
        public string VenueComment_Comment { get; set; }
        public Nullable<System.DateTime> VenueComment_DateTime { get; set; }
    
        public virtual Venue Venue { get; set; }
    }
}
