//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfV400.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public Venue()
        {
            this.Bands = new HashSet<Band>();
            this.Events = new HashSet<Event>();
            this.ReviewVenues = new HashSet<ReviewVenue>();
            this.VenueUsers = new HashSet<VenueUser>();
            this.VenueComments = new HashSet<VenueComment>();
        }
    
        public int Venue_Id { get; set; }
        public string Venue_Name { get; set; }
        public string Venue_AddressLine1 { get; set; }
        public string Venue_AddressLine2 { get; set; }
        public string Venue_City { get; set; }
        public string Venue_PostalCode { get; set; }
        public Nullable<int> Venue_StateProvinceId { get; set; }
        public Nullable<int> Venue_CountryId { get; set; }
        public byte[] Venue_Photo { get; set; }
        public string Venue_PhotoFileName { get; set; }
        public string Venue_PhotoMimeType { get; set; }
        public string Venue_Long { get; set; }
        public string Venue_Lat { get; set; }
        public string Venue_URL { get; set; }
        public string Venue_Description { get; set; }
        public Nullable<bool> Venue_Major { get; set; }
        public Nullable<int> Venue_Capacity { get; set; }
        public string Venue_Architect { get; set; }
        public int Venue_CreatedBy { get; set; }
        public Nullable<System.DateTime> Venue_CreatedDate { get; set; }
    
        public virtual ICollection<Band> Bands { get; set; }
        public virtual CountryRegion CountryRegion { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<ReviewVenue> ReviewVenues { get; set; }
        public virtual StateProvince StateProvince { get; set; }
        public virtual ICollection<VenueUser> VenueUsers { get; set; }
        public virtual ICollection<VenueComment> VenueComments { get; set; }
    }
}
